"""Type definitions for Google Workspace MCP.

Type aliases for Google API services to improve type safety while working
with dynamically-typed Google client libraries.
"""

from typing import Any

# Google API Service Type Aliases
# The actual objects are dynamically generated by googleapiclient.discovery.build()

GoogleDriveService = Any
GoogleDocsService = Any
GoogleSheetsService = Any
GoogleGmailService = Any
GoogleCalendarService = Any
GoogleChatService = Any
GoogleFormsService = Any
GoogleSlidesService = Any
GoogleTasksService = Any
GoogleSearchService = Any
GoogleOAuth2Service = Any

# Common Type Aliases
FileMetadata = dict[str, Any]
MessageMetadata = dict[str, Any]
CalendarEvent = dict[str, Any]
DocumentStructure = dict[str, Any]
